More fixes for wait-for-checks

diff --git a/bin/wait-for-checks b/bin/wait-for-checks
--- a/bin/wait-for-checks
+++ b/bin/wait-for-checks
@@ -12,10 +12,21 @@
 #/   -t|--timeout <TIMEOUT>   Wait <TIMEOUT> seconds for checks to go green (default is 300, 5 minutes)
 #/
 
+if ! type gh >/dev/null 2>&1; then
+  echo "This script requires the 'gh' command."
+  exit 1
+fi
+
+if ! type git >/dev/null 2>&1; then
+  echo "This script requires the 'git' command."
+  exit 1
+fi
+
 usage() {
   cat "$0" | grep "^#/" | cut -c4-
 }
 
+target=
 timeout=300
 while [[ $# -gt 0 ]]; do
   key="$1"
@@ -31,17 +42,26 @@ while [[ $# -gt 0 ]]; do
       exit 0
       ;;
     *)
-      target="$1"
+      target="$key"
       shift
       ;;
   esac
 done
 
-echo "Waiting $timeout seconds for PR checks to complete..."
+if [ -z "$target" ]; then
+  target=$(git rev-parse --abbrev-ref HEAD)
+fi
+
+if gh pr checks "$target" 2>&1 | grep "no pull requests" >/dev/null 2>&1; then
+  echo "Could not find PR checks for '$target'" 1>&2
+  exit 0
+fi
+
+echo "Waiting $timeout seconds for PR checks on '$target' to complete..."
 
 counter=0
 while [[ $counter -lt $timeout ]]; do
-  if gh pr checks "$target" >/dev/null 2>&1; then
+  if gh pr checks $target >/dev/null 2>&1; then
     echo "Checks have completed!"
     notify "🏁 Your build is finished! 🏁"
     exit 0
